import { StyleSheet } from 'react-native';

export const adminScreenStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  container: { padding: 16, paddingBottom: 48 },
  header: { marginBottom: 12 },
  title: { fontSize: 24, fontWeight: '700', color: '#263238' },
  subtitle: { fontSize: 16, color: '#607d8b', marginTop: 8 },
  statsRow: { marginTop: 12, paddingVertical: 6 },
  statCard: {
    width: '100%',
    height: 100,
    backgroundColor: '#fff',
    borderRadius: 8,
    marginBottom: 12,
    padding: 12,
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
  },
  stat_default: { backgroundColor: '#fff' },
  stat_roles: { backgroundColor: '#fff' },
  stat_aprendices: { backgroundColor: '#fff' },
  stat_instructores: { backgroundColor: '#fff' },
  statValue: { fontSize: 24, fontWeight: '700', color: '#020817' },
  statLabel: { fontSize: 14, color: '#525363', marginTop: 6 },
  controlsRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 18 },
  tabsRow: { flexDirection: 'row' },
  tabsBar: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#eef1f6', padding: 6, borderRadius: 12 },
  tabButton: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, marginRight: 6 },
  tabActive: { backgroundColor: '#fff', shadowColor: '#000', shadowOpacity: 0.03, shadowOffset: { width: 0, height: 1 }, shadowRadius: 3, elevation: 1 },
  tabIcon: { marginRight: 8 },
  tabText: { color: '#607d8b', fontWeight: '600' },
  tabTextActive: { color: '#0b2540' },
  actionsRow: { flexDirection: 'row', alignItems: 'center' },
  iconButton: { padding: 8, marginRight: 8, backgroundColor: '#fff', borderRadius: 8 },
  primaryButton: { backgroundColor: '#1a48bc', paddingHorizontal: 12, paddingVertical: 10, borderRadius: 8 },
  primaryButtonText: { color: '#fff', fontWeight: '700' },
  matrixContainer: { marginTop: 20 },
  matrixTitle: { fontSize: 20, fontWeight: '700', color: '#020817' },
  matrixHeaderRow: { flexDirection: 'row', backgroundColor: '#f6f7fb', paddingVertical: 10, borderRadius: 8 },
  matrixRow: { flexDirection: 'row', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#eee' },
  matrixCell: { minWidth: 140, paddingHorizontal: 12, justifyContent: 'center' },
  matrixCellFirst: { minWidth: 160 },
  matrixHeaderText: { fontWeight: '700', color: '#020817' },
  matrixCellText: { color: '#525363' },
  /* simplified mobile matrix */
  matrixSimpleContainer: { marginTop: 12 },
  matrixSimpleHeader: { flexDirection: 'row', paddingVertical: 10, paddingHorizontal: 8, backgroundColor: '#f6f7fb', borderRadius: 8 },
  matrixSimpleCell: { flex: 1, paddingHorizontal: 8, justifyContent: 'center' },
  matrixSimpleHeaderText: { fontWeight: '700', color: '#020817' },
  matrixSimpleRow: { flexDirection: 'row', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#eee', alignItems: 'center' },
  matrixPill: { backgroundColor: '#fff', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999, borderWidth: 1, borderColor: '#eef2f5', alignSelf: 'flex-start' },
  matrixPillText: { color: '#020817' },
  /* new mobile list styles */
  searchBox: { marginTop: 12, backgroundColor: '#fff', borderRadius: 8, padding: 10, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#e6e7ee' },
  searchText: { color: '#607d8b', marginLeft: 8 },
  filterRow: { flexDirection: 'row', gap: 8, marginTop: 10 },
  filterButton: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, backgroundColor: '#fff', marginRight: 8, borderWidth: 1, borderColor: '#e6e7ee' },
  listContainer: { marginTop: 12 },
  userCard: { width: '100%', backgroundColor: '#fff', padding: 12, borderRadius: 10, marginBottom: 12, shadowColor: '#000', shadowOpacity: 0.04, shadowOffset: { width: 0, height: 1 }, shadowRadius: 3, elevation: 1 },
  userName: { fontSize: 14, fontWeight: '700', color: '#020817' },
  userEmail: { fontSize: 12, color: '#607d8b', marginTop: 4 },
  userRoleBadge: { marginTop: 8, backgroundColor: '#f1f5f9', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 999 },
  userActions: { flexDirection: 'row', gap: 8, marginTop: 10 },
  smallButton: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 8, backgroundColor: '#fff', borderWidth: 1, borderColor: '#e6e7ee' },
  roleCard: { width: '100%', backgroundColor: '#fff', padding: 12, borderRadius: 10, marginBottom: 12, alignItems: 'center' },
  /* green variant for enabled users (mobile design) */
  userCardGreen: { width: '100%', backgroundColor: '#e8f9ee', padding: 18, borderRadius: 12, marginBottom: 16, borderWidth: 1, borderColor: '#7fd29a', alignItems: 'center' },
  userStatusBadge: { backgroundColor: '#def7df', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999, marginBottom: 10 },
  userArea: { fontSize: 12, color: '#607d8b', marginTop: 8 },
  userRoleText: { fontSize: 13, fontWeight: '700', marginTop: 6 },
  inhabilitarButton: { backgroundColor: '#d32f2f', paddingVertical: 12, borderRadius: 8, width: '100%', alignItems: 'center', marginTop: 12 },
  inhabilitarText: { color: '#fff', fontWeight: '700' },
  editButtonFull: { marginTop: 8, width: '100%', paddingVertical: 10, borderRadius: 8, borderWidth: 1, borderColor: '#e6e7ee', alignItems: 'center', backgroundColor: '#fff' },
});

export default adminScreenStyles;
