import { StyleSheet } from 'react-native';

export const forgotPasswordScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingHorizontal: 19,
    paddingVertical: 43,
    alignItems: 'center',
    gap: 32,
  },
  backButton: {
    backgroundColor: '#43A047',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    alignSelf: 'stretch',
    justifyContent: 'center',
  },
  backButtonText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '400',
    lineHeight: 20,
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 8,
  },
  appTitle: {
    fontSize: 36,
    fontWeight: '700',
    color: '#43A047',
    textAlign: 'center',
    letterSpacing: -0.6,
    lineHeight: 32,
    marginBottom: 16,
  },
  recoverySection: {
    width: '100%',
    maxWidth: 342,
    alignItems: 'flex-start',
    gap: 12,
  },
  recoveryTitle: {
    fontSize: 30,
    fontWeight: '700',
    color: '#424242',
    lineHeight: 36,
  },
  recoverySubtitle: {
    fontSize: 20,
    fontWeight: '400',
    color: '#757575',
    lineHeight: 20,
  },
  formContainer: {
    width: '100%',
    maxWidth: 295,
    gap: 31,
    alignItems: 'center',
  },
  input: {
    width: '100%',
    height: 57,
    backgroundColor: 'rgba(255, 255, 255, 0)',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#E0E0E0',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  sendButton: {
    width: '100%',
    height: 50,
    backgroundColor: '#388E3C',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  sendButtonText: {
    fontSize: 25,
    fontWeight: '600',
    color: '#FFFFFF',
    lineHeight: 20,
  },
  footerContainer: {
    flexDirection: 'row',
    gap: 20,
    paddingHorizontal: 10,
    marginTop: 20,
  },
  footerLink: {
    fontSize: 12,
    color: '#9E9E9E',
    fontWeight: '400',
    lineHeight: 16,
  },
});
