import { StyleSheet } from 'react-native';

export const registerScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingHorizontal: 19,
    paddingVertical: 43,
    gap: 30,
  },
  backButton: {
    backgroundColor: '#43A047',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    justifyContent: 'center',
  },
  backButtonText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '400',
    lineHeight: 20,
  },
  headerContainer: {
    alignItems: 'center',
    gap: 20,
  },
  appTitle: {
    fontSize: 29,
    fontWeight: '700',
    color: '#43A047',
    textAlign: 'center',
    letterSpacing: -0.6,
    lineHeight: 32,
  },
  titleSection: {
    gap: 27,
    alignItems: 'flex-start',
  },
  registerTitle: {
    fontSize: 30,
    fontWeight: '700',
    color: '#424242',
    lineHeight: 36,
  },
  registerSubtitle: {
    fontSize: 20,
    fontWeight: '400',
    color: '#757575',
    lineHeight: 20,
  },
  formContainer: {
    gap: 16,
  },
  inputFullWidth: {
    width: '100%',
    height: 57,
    backgroundColor: 'rgba(255, 255, 255, 0)',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  rowContainer: {
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  inputHalf: {
    flex: 1,
    height: 57,
    backgroundColor: 'rgba(255, 255, 255, 0)',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  pickerContainer: {
    height: 36,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#C4C4C4',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  pickerText: {
    fontSize: 20,
    fontWeight: '500',
  },
  pickerTextSelected: {
    color: '#424242',
  },
  pickerTextPlaceholder: {
    color: '#757575',
  },
  pickerIconRotated: {
    transform: [{ rotate: '180deg' }],
  },
  pickerDropdown: {
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  pickerOption: {
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  pickerOptionText: {
    fontSize: 16,
    color: '#424242',
  },
  termsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 2,
    height: 29,
  },
  termsTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    flex: 1,
    marginLeft: 8,
  },
  termsText: {
    fontSize: 14,
    color: '#757575',
    lineHeight: 20,
    fontWeight: '400',
  },
  termsLink: {
    fontSize: 14,
    color: '#43A047',
    lineHeight: 20,
    fontWeight: '400',
  },
  registerButton: {
    width: '100%',
    height: 50,
    backgroundColor: '#388E3C',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  registerButtonText: {
    fontSize: 30,
    fontWeight: '600',
    color: '#FFFFFF',
    lineHeight: 20,
  },
  footerContainer: {
    flexDirection: 'row',
    gap: 20,
    paddingHorizontal: 10,
    justifyContent: 'center',
  },
  footerLink: {
    fontSize: 12,
    color: '#9E9E9E',
    fontWeight: '400',
    lineHeight: 16,
  },
});
