import { StyleSheet } from 'react-native';

export const registerScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingHorizontal: 36,
    paddingVertical: 43,
    gap: 30,
  },
  backButton: {
    backgroundColor: '#43A047',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    justifyContent: 'center',
  },
  backButtonText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '400',
    lineHeight: 20,
  },
  headerContainer: {
    alignItems: 'center',
    gap: 20,
  },
  appTitle: {
    fontSize: 32,
    fontWeight: '700',
    color: '#00A859',
    textAlign: 'center',
    letterSpacing: -0.6,
    lineHeight: 32,
  },
  titleSection: {
    gap: 27,
    alignItems: 'flex-start',
  },
  registerTitle: {
    fontSize: 30,
    fontWeight: '700',
    color: '#424242',
    lineHeight: 36,
  },
  registerSubtitle: {
    fontSize: 20,
    fontWeight: '400',
    color: '#757575',
    lineHeight: 20,
  },
  formContainer: {
    gap: 18,
  },
  inputFullWidth: {
    width: '100%',
    height: 56,
    borderRadius: 8,
  },
  rowContainer: {
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  inputHalf: {
    flex: 1,
    height: 56,
    minHeight: 2,
    borderRadius: 8,
  },
  pickerContainer: {
    height: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E9E9E9',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
    boxShadow: '0px 2px 4px rgba(0,0,0,0.06)',
  },
  pickerWrapper: {
    position: 'relative',
    width: '100%',
  },
  pickerText: {
    fontSize: 20,
    fontWeight: '500',
  },
  pickerTextSelected: {
    color: '#424242',
  },
  pickerTextPlaceholder: {
    color: '#757575',
  },
  pickerIconRotated: {
    transform: [{ rotate: '180deg' }],
  },
  pickerDropdown: {
    position: 'absolute',
    top: 58,
    left: 0,
    right: 0,
    width: '100%',
    zIndex: 9999,
    elevation: 20,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E9E9E9',
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    boxShadow: '0px 4px 8px rgba(0,0,0,0.12)',
  },
  pickerOption: {
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  pickerOptionText: {
    fontSize: 12,
    color: '#424242',
  },
  termsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 2,
    height: 36,
  },
  termsTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    flex: 1,
    marginLeft: 8,
  },
  termsText: {
    fontSize: 14,
    color: '#757575',
    lineHeight: 20,
    fontWeight: '400',
  },
  termsLink: {
    fontSize: 14,
    color: '#43A047',
    lineHeight: 20,
    fontWeight: '400',
  },
  registerButton: {
    width: '100%',
    height: 56,
    backgroundColor: '#00A859',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 3,
    boxShadow: '0px 4px 8px rgba(0,0,0,0.12)',
  },
  registerButtonText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
    lineHeight: 24,
  },
  footerContainer: {
    flexDirection: 'row',
    gap: 20,
    paddingHorizontal: 10,
    justifyContent: 'center',
  },
  footerLink: {
    fontSize: 12,
    color: '#9E9E9E',
    fontWeight: '400',
    lineHeight: 16,
  },
});
