import { StyleSheet, Dimensions } from 'react-native';
const { width } = Dimensions.get('window');

export const resetPasswordScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  content: {
    flex: 1,
    paddingHorizontal: 19,
    paddingVertical: 43,
    alignItems: 'center',
    gap: 32,
  },
  backButton: {
    backgroundColor: '#43A047',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    width: '100%',
    minHeight: 48,
    justifyContent: 'flex-start',
  },
  backButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
  },
  logoContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  appTitle: {
    fontSize: 36,
    fontFamily: 'Roboto-Bold',
    fontWeight: '700',
    color: '#43A047',
    letterSpacing: -0.6,
    lineHeight: 32,
    textAlign: 'center',
  },
  headerContainer: {
    width: Math.min(342, width - 38),
    alignItems: 'flex-start',
    gap: 12,
  },
  title: {
    fontSize: 30,
    fontFamily: 'Roboto-Bold',
    fontWeight: '700',
    color: '#424242',
    lineHeight: 36,
    width: '100%',
  },
  description: {
    fontSize: 20,
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
    color: '#757575',
    lineHeight: 20,
    width: '100%',
  },
  formContainer: {
    width: Math.min(342, width - 38),
    alignItems: 'center',
    gap: 20,
  },
  input: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    fontSize: 16,
  },
  inputOutline: {
    borderWidth: 2,
    borderColor: '#E0E0E0',
    borderRadius: 8,
  },
  inputContent: {
    paddingLeft: 52,
    fontSize: 16,
    fontFamily: 'Roboto-Regular',
    color: '#90A4AE',
  },
  errorText: {
    color: '#F44336',
    fontSize: 14,
    fontFamily: 'Roboto-Regular',
    alignSelf: 'flex-start',
    marginTop: 8,
  },
  submitButton: {
    borderRadius: 8,
    elevation: 2,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    width: '100%',
  },
  submitButtonContent: {
    height: 50,
    paddingHorizontal: 10,
    justifyContent: 'center',
  },
  submitButtonLabel: {
    fontSize: 25,
    fontFamily: 'Roboto-SemiBold',
    fontWeight: '600',
    color: '#FFFFFF',
    lineHeight: 20,
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
    paddingHorizontal: 10,
  },
  footerLink: {
    fontSize: 12,
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
    color: '#9E9E9E',
    lineHeight: 16,
  },
});
