import { StyleSheet, Dimensions } from 'react-native';
const { width } = Dimensions.get('window');

export const supportModalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    paddingHorizontal: 36,
    paddingVertical: 10,
    width: Math.min(width - 32, 420),
    maxHeight: '80%',
    elevation: 8,
  },
  header: {
    flexDirection: 'column',
    alignItems: 'center',
    marginBottom: 10,
  },
  closeButton: {
    position: 'absolute',
    left: 8,
    top: 8,
    padding: 8,
  },
  headerPill: {
    borderRadius: 100,
    paddingHorizontal: 10,
    paddingVertical: 9,
    marginBottom: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pillIcon: {
    width: 38,
    height: 38,
  },
  title: {
    fontSize: 20,
    fontWeight: '600',
    color: '#000000',
    textAlign: 'center',
    marginBottom: 6,
  },
  contentInner: {
    paddingBottom: 6,
    alignItems: 'center',
    width: '100%',
  },
  subtitle: {
    fontSize: 20,
    color: '#757575',
    marginBottom: 12,
    textAlign: 'center',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#424242',
    marginTop: 20,
    marginBottom: 8,
    textAlign: 'center',
  },
  imagesContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    gap: 8,
  },
  image: {
    width: '100%',
    height: 164,
    borderRadius: 10,
    marginVertical: 8,
  },
  imageSmall: {
    width: '100%',
    height: 96,
    borderRadius: 10,
    marginVertical: 8,
  },
  imageLarge: {
    width: '100%',
    height: 275,
    borderRadius: 10,
    marginVertical: 8,
  },
  contactText: {
    fontSize: 16,
    color: '#424242',
    marginTop: 18,
    textAlign: 'center',
    lineHeight: 22,
  },
  /* New styles for cards, form and links */
  cardList: {
    width: '100%',
    marginBottom: 12,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 18,
    paddingTop: 28,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  cardIconWrapper: {
    alignSelf: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
    marginBottom: 8,
  },
  cardIcon: {
    fontSize: 18,
  },
  cardTitle: {
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '600',
    marginTop: 8,
    color: '#000',
  },
  cardDesc: {
    textAlign: 'center',
    fontSize: 13,
    color: '#9E9E9E',
    marginTop: 4,
  },
  cardContact: {
    textAlign: 'center',
    fontSize: 16,
    color: '#424242',
    marginTop: 8,
    fontWeight: '600',
  },
  cardFooter: {
    marginTop: 10,
    alignItems: 'center',
  },
  cardFooterText: {
    fontSize: 12,
    color: '#9E9E9E',
  },
  hoursCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  hoursTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#000',
    marginBottom: 8,
  },
  hoursRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  hoursLabel: {
    fontSize: 13,
    color: '#424242',
  },
  hoursValue: {
    fontSize: 13,
    color: '#00A859',
    fontWeight: '600',
  },
  hoursClosed: {
    fontSize: 13,
    color: '#9E9E9E',
  },
  hoursNote: {
    backgroundColor: '#FFF4E6',
    borderRadius: 8,
    padding: 10,
    marginTop: 8,
  },
  hoursNoteText: {
    fontSize: 12,
    color: '#8A6B45',
  },
  formCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 14,
    marginBottom: 12,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  formHeader: {
    marginBottom: 8,
  },
  formHeaderTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#000',
  },
  input: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
    fontSize: 14,
    color: '#212121',
  },
  textArea: {
    minHeight: 90,
    textAlignVertical: 'top',
  },
  submitButton: {
    backgroundColor: '#00A859',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 6,
  },
  submitButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 16,
  },
  linksCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 12,
    marginBottom: 24,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  linksTitle: {
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 8,
  },
  linkRow: {
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
  },
  linkText: {
    color: '#424242',
    fontSize: 14,
  },
});
