import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    backgroundColor: '#fff',
    flex: 1,
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 10,
    gap: 20,
  },
  titulo: {
    fontSize: 25,
    lineHeight: 20,
    textTransform: 'capitalize',
    textAlign: 'center',
    color: '#000',
    fontFamily: 'Roboto-Bold',
    fontWeight: '600',
    marginBottom: 10,
  },
  botonRegistrarParent: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    marginBottom: 16,
  },
  botonRegistrar: {
    backgroundColor: '#1a48bc',
    gap: 5,
    flexDirection: 'row',
    borderRadius: 10,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  registroFormulario: {
    color: '#fff',
    fontFamily: 'Roboto-Bold',
    fontWeight: '600',
    fontSize: 12,
    marginLeft: 4,
  },
  buscar: {
    gap: 5,
    width: '100%',
    marginBottom: 16,
  },
  zoomInParent: {
    borderColor: '#7d7e81',
    borderWidth: 1,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 10,
    marginBottom: 8,
  },
  zoomInIcon: {
    width: 16,
    height: 16,
  },
  buscarPorNombre: {
    fontWeight: '200',
    fontFamily: 'Roboto-Thin',
    textAlign: 'left',
    color: '#000',
    fontSize: 14,
  },
  filtroBorder: {
    borderWidth: 1,
    borderStyle: 'solid',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 10,
    backgroundColor: '#f3f4f6',
  },
  filtro: {
    borderColor: 'rgba(204, 204, 204, 0.47)',
    borderWidth: 1,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 10,
    backgroundColor: '#f3f4f6',
    flex: 1,
  },
  todosLosUsuarios: {
    fontSize: 10,
    fontFamily: 'Inter-Regular',
    color: '#000',
  },
  tarjetas: {
    width: '100%',
    alignItems: 'center',
    gap: 20,
  },
  tarjetaRoles: {
    width: 220,
    gap: 10,
    borderColor: 'rgba(125, 126, 129, 0.41)',
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  frameParent: {
    gap: 10,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gestionAcademicaWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 128,
    height: 32,
  },
  seguridadWrapper: {
    width: 128,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  seguridadTypo: {
    fontFamily: 'Roboto-Medium',
    fontWeight: '500',
    fontSize: 20,
    lineHeight: 32,
    color: '#000',
    textAlign: 'left',
  },
  estados: {
    backgroundColor: 'rgba(67, 160, 71, 0.9)',
    height: 21,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  activo: {
    fontWeight: '700',
    fontFamily: 'Inter-Bold',
    color: '#0c672d',
    fontSize: 12,
    lineHeight: 16,
  },
  administracionDeProcesos: {
    fontFamily: 'Inter-Medium',
    fontWeight: '500',
    color: '#000',
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'center',
    marginBottom: 4,
  },
  tarjetaRolesInner: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  ajustarWrapper: {
    backgroundColor: '#16a34a',
    alignItems: 'center',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  ajustar: {
    fontFamily: 'Inter-SemiBold',
    color: '#fff',
    fontWeight: '600',
    fontSize: 12,
    lineHeight: 16,
  },
});
